config/routes.rb
Rails.application.routes.draw do
  root 'cabnets#index'
  resources :cabnets

  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-in', to: 'auth#new'
  post 'sign-in', to: 'auth#create'
  get 'sign-out', to: 'auth#destroy'
end

app/models/cabnet.rb
class Cabnet < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def ensure_current_user
    notice = 'You are not logged in!'
    redirect_to root_path, notice: notice unless current_user
  end
  
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'Thank you for signing in!'
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    reset_session
    flash[:notice] = 'Thank you for logging out!'
    redirect_to root_path
  end
  
end

app/controllers/cabnets_controller.rb
class CabnetsController < ApplicationController
  before_action :set_cabnet, only:[:show, :edit, :update]

  def index
    @cabnets = Cabnet.all
  end

  def show
  end

  def new
    @cabnet = Cabnet.new
  end

  def create
    cabnet = Cabnet.new(cabnet_params)
    if cabnet.save
      flash[:notice] = 'Thank you for making a new cabnet'
      redirect_to cabnet_path(cabnet)
    else
      @cabnet = cabnet
      render :new
    end
  end

  def edit
  end

  def update
    if @cabnet.update(cabnet_params)
      flash[:notice] = 'Cabnet is updated'
      redirect_to cabnet_path(@cabnet)
    else
      render :edit
    end
  end

  def destroy
    cabnet = Cabnet.find(params[:id])
    cabnet.destroy
    flash[:notice] = 'Goodbye!'
    redirect_to root_path
  end

  private

  def cabnet_params
    params.require(:cabnet).permit(:name)
  end

  def set_cabnet
    @cabnet = Cabnet.find(params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(params.require(:user).permit(:email, :password))
    if user.save
      session[:user_id] = user.id
      flash[:notice] = 'Thank you for signing in!'
      redirect_to root_path
    else
      @user = user
      render :new
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cabnets/_form.haml
= form_for @cabnet do |f|
  = f.label :name
  = f.text_field :name
  = f.submit

app/views/cabnets/edit.haml
= render 'form'

app/views/cabnets/index.haml
list of cabnets
= link_to 'New Cabnet', new_cabnet_path
- @cabnets.each do |cabnet|
  = "Cabnet name: #{cabnet.name}."
  = link_to 'Edit', edit_cabnet_path(cabnet)
  = link_to 'Delete', cabnet_path(cabnet), method: :delete

app/views/cabnets/new.haml
= render 'form'

app/views/cabnets/show.haml
= @cabnet.name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Computer
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if flash[:notice]
      = flash[:notice]
    - if current_user
      = link_to 'Sign Out', sign_out_path
    - else
      = link_to 'Sign In', sign_in_path
      = link_to 'Sign Up', sign_up_path
    = yield